jdbc:
  default:
    url: jdbc:mysql://localhost:3306/testdb?verifyServerCertificate=false&useSSL=false
    initialSize: 1
    username: root
    password:

jooq:
  dialect: MYSQL
  executeLogging: true